export const UI_CSS = [
  "*, *::before, *::after { box-sizing: border-box; }",
  "body { margin: 0; font-family: system-ui, sans-serif; background: #0b0c10; color: #e8eaed; }",
  "#app { min-height: 100vh; }",
  ".ui-loading { font-size: 0.95rem; letter-spacing: 0.02em; }",
  ".ui-shell { min-height: 100vh; display: grid; grid-template-rows: auto 1fr; max-width: 100vw; overflow-x: hidden; }",
  ".ui-shell nav { display: flex; flex-wrap: wrap; gap: 0.75rem; padding: 0.75rem 1rem; border-bottom: 1px solid #2a2f3a; }",
  ".ui-shell nav a { color: #9ecbff; }",
  ".ui-shell main, .ui-shell > :not(nav) { padding: 1rem; min-width: 0; }",
  ".preflight-view { display: grid; gap: 1rem; max-width: 100%; }",
  ".preflight-section { display: grid; gap: 0.5rem; min-width: 0; }",
  ".preflight-section h2 { margin: 0; font-size: 1.1rem; }",
  ".data-table { width: 100%; border-collapse: collapse; }",
  ".data-table-wrapper, .preflight-section { overflow-x: auto; max-width: 100%; }",
  ".data-table th, .data-table td { text-align: left; padding: 0.35rem 0.5rem; border-bottom: 1px solid #2a2f3a; vertical-align: top; }",
  ".data-table caption { text-align: left; margin-bottom: 0.5rem; }",
  ".status-badge { display: inline-block; padding: 0.1rem 0.45rem; border-radius: 0.25rem; font-size: 0.85rem; }",
  ".sync-banner { padding: 0.5rem 0.75rem; border: 1px solid #2a2f3a; border-radius: 0.35rem; }",
  "button, input, label { font: inherit; }",
  "button:focus-visible, input:focus-visible, a:focus-visible { outline: 2px solid #9ecbff; outline-offset: 2px; }",
  "@media (max-width: 640px) {",
  "  .preflight-view { grid-template-columns: 1fr; }",
  "  .preflight-section { width: 100%; }",
  "  .ui-shell nav { flex-direction: column; align-items: flex-start; }",
  "}",
  "@media (min-width: 641px) {",
  "  .preflight-view { grid-template-columns: minmax(0, 1fr); }",
  "}",
].join("\n");
