/**
 * Approved Quirks UI visual system.
 *
 * Source of truth: docs/visual-references/quirks-ui/ (approval-workspace-v3,
 * tasks-and-campaign-history-v4, task-provenance-history-v5) via
 * docs/superpowers/design/2026-07-23-quirks-ui-design-handoff.md — light
 * #f3f6fa canvas under a dark #111827 nav shell, white bordered panels,
 * micro-label density, tinted status pills, agent identity colors, and
 * structural breakpoints at 900px / 620px. Ink resolves to #182230 (handoff
 * §6.G). No remote assets; every rule ships through the nonce'd style tag.
 */
export const UI_CSS = [
  ":root {",
  "  --ui-ink: #182230;",
  "  --ui-muted: #667085;",
  "  --ui-line: #dfe5ee;",
  "  --ui-canvas: #f3f6fa;",
  "  --ui-panel: #ffffff;",
  "  --ui-nav: #111827;",
  "  --ui-link: #2563eb;",
  "  --ui-success: #166534;",
  "  --ui-warning: #b45309;",
  "  --ui-danger: #b42318;",
  "  --ui-claude: #d97706;",
  "  --ui-claude-bg: #fffbeb;",
  "  --ui-codex: #0284c7;",
  "  --ui-codex-bg: #f0f9ff;",
  "  --ui-cursor: #7c3aed;",
  "  --ui-cursor-bg: #faf5ff;",
  "  --z-menu: 10;",
  "  --z-footer: 30;",
  "  --z-dialog: 40;",
  "}",
  "*, *::before, *::after { box-sizing: border-box; }",
  "body { margin: 0; font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: var(--ui-canvas); color: var(--ui-ink); font-size: 13px; line-height: 1.45; }",
  "#app { min-height: 100vh; }",
  ".ui-loading { font-size: 0.95rem; letter-spacing: 0.02em; padding: 1rem; }",
  ".ui-shell { min-height: 100vh; display: grid; grid-template-rows: auto 1fr; max-width: 100vw; overflow-x: hidden; }",
  ".ui-shell nav { background: var(--ui-nav); color: #fff; }",
  ".nav-inner { max-width: 1280px; margin: 0 auto; padding: 13px 22px; display: flex; align-items: center; gap: 22px; }",
  ".brand { font-weight: 800; font-size: 16px; letter-spacing: 0.01em; }",
  ".nav-links { display: flex; gap: 5px; margin-left: auto; flex-wrap: wrap; }",
  ".ui-shell nav a { color: #cbd5e1; text-decoration: none; font-size: 12px; padding: 7px 10px; border-radius: 6px; }",
  ".ui-shell nav a[data-status='active'], .ui-shell nav a[aria-current='page'] { background: #273449; color: #fff; }",
  ".ui-shell main, .ui-shell > :not(nav) { width: min(1280px, 100%); margin: 0 auto; padding: 18px 22px 30px; min-width: 0; }",
  "a { color: #1d4ed8; }",
  "button, input, label, textarea { font: inherit; }",
  "button { border: 1px solid #cbd5e1; background: #fff; border-radius: 7px; padding: 8px 11px; font-size: 12px; font-weight: 600; color: #344054; cursor: pointer; }",
  "button:disabled { opacity: 0.55; cursor: not-allowed; }",
  "button:focus-visible, input:focus-visible, a:focus-visible, textarea:focus-visible { outline: 2px solid var(--ui-link); outline-offset: 2px; }",
  "input[type='search'], input[type='text'] { border: 1px solid #cbd5e1; border-radius: 6px; padding: 7px 9px; font-size: 12px; color: var(--ui-ink); background: #fff; }",
  "input::placeholder { color: var(--ui-muted); opacity: 1; }",
  /* Micro-label density system: small bold muted labels above bold values. */
  ".micro-label { display: block; color: var(--ui-muted); font-size: 10px; font-weight: 750; letter-spacing: 0.05em; text-transform: uppercase; }",
  ".workspace-crumb { font-size: 11px; color: var(--ui-muted); margin: 0 0 8px; }",
  /* Workspace header (v3 topbar block / v4 intro / v5 head). */
  ".workspace-header { display: flex; justify-content: space-between; align-items: flex-start; gap: 16px; margin: 0 0 13px; flex-wrap: wrap; }",
  ".workspace-header h1 { font-size: 21px; margin: 3px 0; font-weight: 750; }",
  ".workspace-header p { font-size: 12px; color: var(--ui-muted); margin: 2px 0 0; max-width: 72ch; }",
  ".workspace-header-side { display: flex; flex-direction: column; align-items: flex-end; gap: 8px; min-width: 0; }",
  ".workspace-badges { display: flex; gap: 6px; flex-wrap: wrap; justify-content: flex-end; }",
  ".workspace-header-actions { display: flex; gap: 8px; flex-wrap: wrap; justify-content: flex-end; min-width: 0; }",
  /* Notices (v3 blue immutability notice, v5 amber coordination notice). */
  ".workspace-notice { display: flex; justify-content: space-between; align-items: center; gap: 14px; border: 1px solid var(--ui-line); border-radius: 10px; padding: 11px 13px; margin: 0 0 13px; font-size: 12px; background: var(--ui-panel); }",
  ".workspace-notice strong { display: block; margin-bottom: 2px; }",
  ".workspace-notice-aside { color: var(--ui-muted); white-space: nowrap; }",
  ".workspace-notice--info { background: #eef6ff; border-color: #bfdbfe; }",
  ".workspace-notice--warning { background: #fffbeb; border-color: #fde68a; color: #854d0e; }",
  /* Summary metric strip (v3 5-up, v4 stat cards, v5 6-up). */
  ".summary-grid { display: grid; grid-template-columns: repeat(5, minmax(0, 1fr)); gap: 8px; margin: 0 0 12px; }",
  ".summary-grid[data-columns='6'] { grid-template-columns: repeat(6, minmax(0, 1fr)); }",
  ".summary-grid[data-columns='4'] { grid-template-columns: repeat(4, minmax(0, 1fr)); }",
  ".summary-stat { background: var(--ui-panel); border: 1px solid var(--ui-line); border-radius: 9px; padding: 10px 12px; min-width: 0; }",
  ".summary-stat > span { display: block; color: var(--ui-muted); font-size: 10px; font-weight: 750; letter-spacing: 0.05em; text-transform: uppercase; }",
  ".summary-stat > strong { display: block; margin-top: 3px; font-size: 15px; overflow-wrap: anywhere; }",
  ".summary-stat > small { display: block; color: var(--ui-muted); font-size: 10.5px; margin-top: 2px; }",
  /* Toolbar (v4 search + filter chips row). */
  ".workspace-toolbar { display: flex; gap: 7px; align-items: center; background: var(--ui-panel); border: 1px solid var(--ui-line); border-radius: 9px; padding: 8px; margin: 0 0 10px; flex-wrap: wrap; }",
  ".workspace-toolbar input[type='search'] { flex: 1; min-width: 160px; }",
  ".toolbar-chip { border-radius: 6px; padding: 7px 9px; font-size: 11px; }",
  ".toolbar-chip[aria-pressed='true'] { background: #eff6ff; border-color: #93c5fd; color: #1d4ed8; }",
  ".toolbar-note { margin-left: auto; color: var(--ui-muted); font-size: 10.5px; }",
  ".workspace-toolbar--embedded { border: 0; border-bottom: 1px solid var(--ui-line); border-radius: 0; margin: 0; }",
  ".workspace-toolbar label { font-size: 12px; font-weight: 600; color: var(--ui-muted); }",
  /* Two-column workspace: primary panel + inspector aside. */
  ".workspace-layout { display: grid; grid-template-columns: minmax(0, 2.1fr) minmax(280px, 0.8fr); gap: 12px; align-items: start; }",
  ".workspace-stack { display: grid; gap: 12px; align-content: start; min-width: 0; }",
  ".panel-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 12px; margin: 12px 0 0; }",
  ".panel-grid-wide { grid-column: 1 / -1; min-width: 0; }",
  /* Panels. */
  ".workspace-panel { background: var(--ui-panel); border: 1px solid var(--ui-line); border-radius: 10px; min-width: 0; overflow: hidden; }",
  ".workspace-panel > header { display: flex; justify-content: space-between; gap: 12px; align-items: baseline; padding: 11px 13px; border-bottom: 1px solid var(--ui-line); }",
  ".workspace-panel > header > strong { font-size: 12.5px; }",
  ".workspace-panel > header > span { font-size: 10.5px; color: var(--ui-muted); text-align: right; }",
  ".workspace-panel-body { padding: 12px 13px; }",
  ".workspace-panel-body--flush { padding: 0; }",
  ".workspace-panel-body > p { margin: 6px 0; font-size: 12px; }",
  ".workspace-panel-body > ul { margin: 6px 0; padding-left: 18px; font-size: 12px; }",
  ".panel-footer { border-top: 1px solid var(--ui-line); padding: 10px 13px; display: flex; justify-content: space-between; align-items: center; gap: 10px; font-size: 11.5px; color: var(--ui-muted); flex-wrap: wrap; }",
  ".safety-note { background: #f8fafc; border-radius: 7px; padding: 8px 10px; font-size: 11px; color: var(--ui-muted); }",
  /* Status pills. */
  ".status-badge { display: inline-block; padding: 4px 9px; border-radius: 999px; font-size: 11px; font-weight: 600; white-space: nowrap; }",
  ".status-badge--neutral { background: #f2f4f7; color: #475467; }",
  ".status-badge--info { background: #dbeafe; color: #1d4ed8; }",
  ".status-badge--success { background: #dcfce7; color: var(--ui-success); }",
  ".status-badge--warning { background: #fef3c7; color: #92400e; }",
  ".status-badge--danger { background: #fee4e2; color: var(--ui-danger); }",
  /* Sync meta line (v4 'refreshed n seconds ago' idiom, content contract intact). */
  ".sync-banner { display: flex; flex-wrap: wrap; gap: 6px 12px; align-items: center; font-size: 11.5px; color: var(--ui-muted); margin: 0 0 10px; }",
  /* Tables scroll inside their panel, never the page. */
  ".data-table-wrapper { overflow-x: auto; max-width: 100%; }",
  ".data-table { width: 100%; border-collapse: collapse; font-size: 12px; }",
  ".data-table-wrapper .data-table { min-width: 680px; }",
  ".data-table caption { position: absolute; width: 1px; height: 1px; overflow: hidden; clip: rect(0 0 0 0); white-space: nowrap; }",
  ".data-table th { text-align: left; color: var(--ui-muted); font-size: 10.5px; font-weight: 700; padding: 8px 10px; background: #f8fafc; }",
  ".data-table td { padding: 9px 10px; border-top: 1px solid var(--ui-line); vertical-align: top; }",
  ".data-table tr[data-selected='true'] td { background: #eff6ff; }",
  ".data-table-empty { padding: 12px 13px; margin: 0; font-size: 12px; color: var(--ui-muted); }",
  ".task-select { border: 0; background: none; padding: 0; border-radius: 0; text-align: left; font: inherit; color: inherit; display: block; cursor: pointer; }",
  ".task-subtitle { display: block; color: var(--ui-muted); font-size: 11px; margin-top: 2px; }",
  ".cell-note { display: block; color: var(--ui-muted); font-size: 11px; }",
  ".agent-pill { display: inline-flex; align-items: center; gap: 5px; white-space: nowrap; }",
  ".legend-dot { display: inline-block; width: 8px; height: 8px; border-radius: 2px; }",
  ".legend-dot--claude { background: var(--ui-claude); }",
  ".legend-dot--codex { background: var(--ui-codex); }",
  ".legend-dot--cursor { background: var(--ui-cursor); }",
  ".legend-dot--control { background: #334155; }",
  /* Execution wave map (v3) and dependency frontier (v4). */
  ".wave-map-scroll { overflow-x: auto; padding: 13px; }",
  ".wave-map { display: flex; gap: 6px; min-width: 700px; align-items: stretch; }",
  ".wave-col-group { display: flex; gap: 6px; flex: 1; min-width: 0; }",
  ".wave-col { flex: 1; min-width: 150px; }",
  ".wave-col-label { color: var(--ui-muted); font-size: 10px; font-weight: 750; letter-spacing: 0.04em; margin-bottom: 6px; text-transform: uppercase; }",
  ".wave-arrow { align-self: center; color: #94a3b8; font-size: 16px; padding: 0 2px; }",
  ".task-card { border: 2px solid #cbd5e1; border-radius: 9px; padding: 9px; margin-bottom: 7px; background: #f8fafc; font-size: 11px; min-width: 0; }",
  ".task-card:last-child { margin-bottom: 0; }",
  ".task-card--claude { border-color: var(--ui-claude); background: var(--ui-claude-bg); }",
  ".task-card--codex { border-color: var(--ui-codex); background: var(--ui-codex-bg); }",
  ".task-card--cursor { border-color: var(--ui-cursor); background: var(--ui-cursor-bg); }",
  ".task-card-id { font-size: 10px; font-weight: 750; color: var(--ui-muted); overflow-wrap: anywhere; }",
  ".task-card-owner { font-size: 11px; font-weight: 600; margin-top: 4px; overflow-wrap: anywhere; }",
  ".task-card-score { color: var(--ui-muted); font-size: 10px; margin-top: 3px; }",
  ".wave-legend { display: flex; gap: 12px; flex-wrap: wrap; padding: 10px 13px; border-top: 1px solid var(--ui-line); color: var(--ui-muted); font-size: 10.5px; align-items: center; }",
  ".wave-legend .legend-dot { margin-right: 4px; vertical-align: baseline; }",
  ".frontier-scroll { overflow-x: auto; padding: 10px 13px; border-bottom: 1px solid var(--ui-line); }",
  ".frontier-map { display: flex; gap: 6px; min-width: 650px; align-items: stretch; }",
  ".mini-card { border: 1px solid var(--ui-line); border-radius: 7px; padding: 7px 8px; margin-bottom: 5px; font-size: 11px; background: #fff; }",
  ".mini-card:last-child { margin-bottom: 0; }",
  ".mini-card--ready { border-color: #86efac; background: #f0fdf4; }",
  ".mini-card--blocked { border-color: #cbd5e1; background: #f8fafc; color: #475467; }",
  ".mini-card--design { border-color: #fbbf24; background: #fffbeb; }",
  ".mini-card--claimed { border-color: #93c5fd; background: #eff6ff; }",
  ".mini-card--conflict { border-color: #fda29b; background: #fef3f2; }",
  /* Inspector aside (v3/v4 selected-task detail). */
  ".workspace-inspector { padding: 13px; }",
  ".workspace-inspector h2 { font-size: 16px; margin: 4px 0 10px; }",
  ".workspace-inspector p { font-size: 12px; margin: 5px 0; line-height: 1.45; }",
  ".detail-label { display: block; color: var(--ui-muted); font-size: 10px; font-weight: 750; letter-spacing: 0.05em; text-transform: uppercase; margin: 12px 0 5px; }",
  ".reason-box { background: #eff6ff; border: 1px solid #bfdbfe; border-radius: 8px; padding: 9px 10px; font-size: 11.5px; line-height: 1.45; }",
  ".reason-box strong { display: block; font-size: 12px; margin-bottom: 3px; }",
  ".score-row { display: grid; grid-template-columns: repeat(3, 1fr); gap: 6px; margin: 10px 0; }",
  ".score-cell { background: #f8fafc; border-radius: 7px; padding: 7px 8px; min-width: 0; }",
  ".score-cell > span { display: block; color: var(--ui-muted); font-size: 9.5px; font-weight: 750; letter-spacing: 0.04em; text-transform: uppercase; }",
  ".score-cell > strong { font-size: 12px; }",
  ".inspector-empty { color: var(--ui-muted); font-size: 12px; margin: 4px 0; }",
  /* Campaigns: active-campaign promotion (v4). */
  ".active-campaign { display: flex; justify-content: space-between; align-items: center; gap: 12px; padding: 12px 13px; border-bottom: 1px solid var(--ui-line); background: #f0fdf4; flex-wrap: wrap; }",
  ".active-campaign h3 { font-size: 13px; margin: 4px 0 2px; }",
  ".active-campaign p { font-size: 11px; color: var(--ui-muted); margin: 0; }",
  ".active-campaign a { font-weight: 700; font-size: 11.5px; }",
  /* Timeline steps (v4 selected-campaign rail; campaign detail waves). */
  ".wave-steps { margin: 0; padding: 0; list-style: none; }",
  ".wave-steps li { display: grid; grid-template-columns: 14px 1fr auto; gap: 8px; align-items: start; padding: 7px 0; border-top: 1px solid #eef1f5; font-size: 12px; }",
  ".wave-steps li:first-child { border-top: 0; }",
  ".step-dot { width: 10px; height: 10px; border-radius: 50%; background: #cbd5e1; margin-top: 3px; }",
  /* Plan progress ledger (spec §22 vertical execution ledger). */
  ".plan-progress-ledger h2 { font-size: 13px; margin: 0 0 6px; }",
  ".plan-progress-ledger p { font-size: 12px; margin: 4px 0; }",
  ".plan-progress-ledger ol { list-style: none; margin: 8px 0; padding: 0; }",
  ".plan-progress-ledger ol li { display: flex; justify-content: space-between; gap: 10px; padding: 7px 0; border-top: 1px solid #eef1f5; font-size: 12px; }",
  ".plan-progress-ledger ol li > span:last-child { white-space: nowrap; font-weight: 600; color: var(--ui-muted); }",
  ".plan-progress-ledger ol li[data-status='reported_complete'] > span:last-child { color: #92400e; }",
  ".plan-progress-ledger ol li[data-status='reviewed'] > span:last-child { color: var(--ui-success); }",
  ".plan-progress-ledger ol li[data-status='active'] > span:last-child { color: #1d4ed8; }",
  ".plan-progress-ledger ol li[data-status='failed'] > span:last-child, .plan-progress-ledger ol li[data-status='blocked'] > span:last-child { color: var(--ui-danger); }",
  /* Task history (v5): artifact cards, iteration timeline, provenance rail. */
  ".artifact-cards { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 7px; padding: 10px 13px; margin: 0; list-style: none; }",
  ".artifact-card { border: 1px solid var(--ui-line); border-radius: 8px; padding: 9px; min-width: 0; font-size: 11.5px; }",
  ".artifact-path { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 10.5px; color: #475467; overflow-wrap: anywhere; margin: 3px 0; }",
  ".artifact-meta { font-size: 10.5px; color: var(--ui-muted); margin: 5px 0; }",
  ".artifact-actions { display: flex; gap: 5px; flex-wrap: wrap; margin: 7px 0 0; padding: 0; list-style: none; }",
  ".artifact-actions a { display: inline-block; border: 1px solid #cbd5e1; border-radius: 6px; padding: 5px 7px; font-size: 10.5px; font-weight: 600; color: #344054; text-decoration: none; }",
  ".artifact-actions a.artifact-action--primary { background: #eff6ff; border-color: #93c5fd; color: #1d4ed8; }",
  ".iteration-card { padding: 11px 13px; border-top: 1px solid var(--ui-line); }",
  ".iteration-card:first-of-type { border-top: 0; }",
  ".iteration-top { display: flex; justify-content: space-between; gap: 12px; align-items: flex-start; }",
  ".iteration-outcome { font-size: 12.5px; font-weight: 700; margin: 2px 0; overflow-wrap: anywhere; }",
  ".provenance-rail { display: grid; gap: 12px; align-content: start; min-width: 0; }",
  ".rail-panel { padding: 11px 13px; }",
  ".identity-list { list-style: none; margin: 0; padding: 0; }",
  ".identity-list li { display: flex; justify-content: space-between; gap: 8px; align-items: center; padding: 6px 0; border-top: 1px solid #eef1f5; font-size: 11.5px; flex-wrap: wrap; }",
  ".identity-list li:first-child { border-top: 0; }",
  /* Preflight approval footer (v3): digest + the one irreversible action. */
  ".preflight-view { padding-bottom: 110px; }",
  ".approval-footer { position: fixed; z-index: var(--z-footer); bottom: 0; left: 0; right: 0; background: rgba(255, 255, 255, 0.97); border-top: 1px solid #cbd5e1; box-shadow: 0 -8px 24px rgba(15, 23, 42, 0.08); }",
  ".approval-footer-inner { max-width: 1280px; margin: 0 auto; padding: 12px 22px; display: flex; gap: 10px 16px; align-items: center; justify-content: space-between; flex-wrap: wrap; }",
  ".approval-digest { min-width: 0; flex: 1 1 320px; }",
  ".digest-code { display: block; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 11px; overflow-wrap: anywhere; }",
  ".approval-digest p { margin: 3px 0 0; font-size: 10.5px; color: var(--ui-muted); }",
  ".approval-actions { display: flex; flex-direction: column; gap: 6px; align-items: flex-end; flex-shrink: 0; }",
  ".approval-actions form { display: flex; gap: 10px; align-items: center; flex-wrap: wrap; justify-content: flex-end; }",
  ".approval-actions label { font-size: 11.5px; display: flex; gap: 6px; align-items: flex-start; max-width: 46ch; }",
  ".approval-actions button[type='submit'] { background: var(--ui-success); border-color: var(--ui-success); color: #fff; }",
  ".approval-message { margin: 0; font-size: 11.5px; }",
  /* Prompt/copy surfaces (handoff §4 placements; light-theme containment). */
  ".prompt-actions { display: grid; gap: 8px; margin: 0; min-width: 0; justify-items: start; }",
  ".prompt-actions-buttons { display: flex; flex-wrap: wrap; gap: 8px; align-items: center; margin: 0; }",
  ".prompt-actions-menu { list-style: none; margin: 0; padding: 8px; border: 1px solid var(--ui-line); border-radius: 8px; background: var(--ui-panel); box-shadow: 0 8px 24px rgba(15, 23, 42, 0.08); display: grid; gap: 6px; z-index: var(--z-menu); }",
  ".prompt-actions-menu li { display: flex; flex-wrap: wrap; gap: 6px; }",
  ".prompt-actions-warnings { margin: 0; padding-left: 18px; color: #92400e; font-size: 11.5px; }",
  ".prompt-actions-fallback { width: 100%; }",
  ".prompt-actions-fallback textarea { width: 100%; max-width: 100%; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 11px; background: #f8fafc; color: var(--ui-ink); border: 1px solid #cbd5e1; border-radius: 7px; padding: 8px; }",
  ".prompt-preview { position: static; width: 100%; max-width: 100%; background: var(--ui-panel); color: var(--ui-ink); border: 1px solid var(--ui-line); border-radius: 10px; padding: 12px 13px; display: grid; gap: 8px; font-size: 12px; z-index: var(--z-dialog); }",
  ".prompt-preview h3 { margin: 0; font-size: 13px; }",
  ".prompt-preview-text { overflow-x: auto; max-width: 100%; white-space: pre-wrap; background: #f8fafc; border: 1px solid var(--ui-line); padding: 9px; border-radius: 7px; font-size: 11px; }",
  ".prompt-preview-actions { display: flex; gap: 8px; margin: 0; }",
  /* Structural breakpoints (~900px and 620px per the references). */
  "@media (max-width: 900px) {",
  "  .summary-grid, .summary-grid[data-columns='4'] { grid-template-columns: repeat(2, minmax(0, 1fr)); }",
  "  .summary-grid[data-columns='6'] { grid-template-columns: repeat(3, minmax(0, 1fr)); }",
  "  .workspace-layout { grid-template-columns: 1fr; }",
  "  .panel-grid { grid-template-columns: 1fr; }",
  "  .artifact-cards { grid-template-columns: 1fr; }",
  "  .toolbar-note { display: none; }",
  "  .approval-actions { align-items: flex-start; }",
  "}",
  "@media (max-width: 620px) {",
  "  .ui-shell main, .ui-shell > :not(nav) { padding: 14px 13px 24px; }",
  "  .nav-inner { padding: 12px 13px; flex-wrap: wrap; gap: 10px; }",
  "  .workspace-header, .workspace-notice { flex-direction: column; align-items: flex-start; }",
  "  .workspace-header-side { align-items: flex-start; }",
  "  .workspace-badges, .workspace-header-actions { justify-content: flex-start; }",
  "  .summary-grid, .summary-grid[data-columns='6'], .summary-grid[data-columns='4'] { grid-template-columns: 1fr 1fr; }",
  "  .workspace-toolbar input[type='search'] { flex-basis: 100%; }",
  "  .toolbar-note { margin-left: 0; }",
  "  .approval-footer-inner { flex-direction: column; align-items: stretch; }",
  "  .approval-actions, .approval-actions form { align-items: stretch; width: 100%; }",
  "  .approval-actions button[type='submit'] { width: 100%; }",
  "}",
].join("\n");
